export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN_SEND_OTP: '/api/auth/login/send-otp',
    LOGIN_VERIFY_OTP: '/api/auth/login/verify-otp',
    LOGIN_PASSWORD: '/api/auth/login/password',
    REGISTER_SEND_OTP: '/api/auth/register/send-otp',
    REGISTER_VERIFY_OTP: '/api/auth/register/verify-otp',
    REGISTER_DIRECT: '/api/auth/register/direct',
    SET_PASSWORD: '/api/auth/set-password',
    PROFILE: '/api/auth/profile',
  },
  EVENTS: {
    CREATE: '/api/events',
    MY_EVENTS: '/api/events/my-events',
    BY_CODE: (code: string) => `/api/events/code/${code}`,
    BY_SLUG: (slug: string) => `/api/events/slug/${slug}`,
    FIND: (identifier: string) => `/api/events/find/${identifier}`,
    BY_ID: (id: string) => `/api/events/${id}`,
    UPDATE_SLUG: (id: string) => `/api/events/${id}/slug`,
    SHARING_PERMISSIONS: (id: string) => `/api/events/${id}/sharing-permissions`,
    GUEST_LIST_FILE: (id: string) => `/api/events/${id}/guest-list-file`,
  },
  PHOTOS: {
    PRESIGNED_URL: '/api/photos/presigned-url',
    COMPLETE: '/api/photos/complete',
    MATCH: '/api/photos/match',
    GUEST_UPLOAD: '/api/photos/guest-upload',
    GUEST_PRESIGNED_URL: '/api/photos/guest-presigned-url',
    GUEST_COMPLETE: '/api/photos/guest-complete',
    EVENT_PHOTOS: (eventId: string) => `/api/photos/event/${eventId}`,
    EVENT_STORY_GROUPS: (eventId: string) => `/api/photos/event/${eventId}/story-groups`,
    DOWNLOAD: (id: string) => `/api/photos/download/${id}`,
    DOWNLOAD_URL: (id: string) => `/api/photos/download-url/${id}`,
    DOWNLOAD_ZIP: '/api/photos/download-zip',
    DELETE: (id: string) => `/api/photos/${id}`,
    SHOWCASE_IMAGES: '/api/photos/showcase/images',
  },
  FACES: {
    EVENT_FACES: (eventId: string) => `/api/faces/event/${eventId}/faces`,
    FACE_PHOTOS: (eventId: string, faceId: string) => `/api/faces/event/${eventId}/face/${faceId}/photos`,
    FACE_DOWNLOAD: (eventId: string, faceId: string) => `/api/faces/event/${eventId}/face/${faceId}/download`,
  },
  PAYMENT: {
    CREATE: '/api/payment/create',
    CHARGE: '/api/payment/charge',
    SUMIT_REDIRECT_BEGIN: '/api/payment/sumit-redirect/begin',
    SUMIT_REDIRECT_VERIFY: '/api/payment/sumit-redirect/verify',
    PAY_WITH_COUPON: '/api/payment/pay-with-coupon',
    STATUS: (eventId: string) => `/api/payment/event/${eventId}/status`,
    HISTORY: '/api/payment',
    BY_ID: (paymentId: string) => `/api/payment/${paymentId}`,
  },
  COUPONS: {
    VALIDATE: '/api/coupons/validate',
    CREATE: '/api/coupons',
    LIST: '/api/coupons',
    ACTIVE_STANDARD: '/api/coupons/active-standard',
    DEACTIVATE: (couponId: string) => `/api/coupons/${couponId}/deactivate`,
  },
  AFFILIATE: {
    REGISTER: '/api/affiliate/register',
    LOGIN: '/api/affiliate/login',
    ME: '/api/affiliate/me',
    WITHDRAWALS: '/api/affiliate/me/withdrawals',
    PREPAID: '/api/affiliate/me/prepaid',
    STATS: (id: string) => `/api/affiliate/${id}/stats`,
    REFERRALS: (id: string) => `/api/affiliate/${id}/referrals`,
  },
  CONTACT: {
    SUBMIT: '/api/contact/submit',
  },
  REVIEWS: {
    SUBMIT: '/api/reviews/submit',
    APPROVED: '/api/reviews/approved',
  },
  GUESTS: {
    ADD: (eventId: string) => `/api/guests/event/${eventId}`,
    BULK: (eventId: string) => `/api/guests/event/${eventId}/bulk`,
    LIST: (eventId: string) => `/api/guests/event/${eventId}`,
    UPDATE: (eventId: string, guestId: string) => `/api/guests/event/${eventId}/${guestId}`,
    DELETE: (eventId: string, guestId: string) => `/api/guests/event/${eventId}/${guestId}`,
    DELETE_ALL: (eventId: string) => `/api/guests/event/${eventId}`,
  },
  HEALTH: '/health',
};
